spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: yu
    username: yu
    password: 2023
#    #生产者确认  产生额外网络和系统资源开销,尽量不使用
#    publisher-confirm-type: correlated   #MQ异步回调方式返回回执消息
#    publisher-returns: true     #返回错误原因--路由失败-交换机->队列错误
#    #生产者重连
#    connection-timeout: 1s   #设置MQ的连接超时时间
#    #建议禁用重试机制  -- 阻塞式 -- 影响业务性能
#    template:
#      retry:
#        enabled: true        #开启超时重试机制
#        initial-interval: 1000ms       #失败后的初始等待时间
#        multiplier: 2      #失败后下次的等待时长倍数,下次等待时长 = initial-interval * multiplier
#        max-attempts: 3    #最大重试次数